CREATE DATABASE LIMPEZA;
USE LIMPEZA;

CREATE TABLE CLIENTE(
CODCLI INT NOT NULL,
NOMECLI VARCHAR(35),
FONECLI VARCHAR(25),
ENDCLI VARCHAR(35),
LIMCREDCLI CHAR(35),
STATUSCLI CHAR(35)
);

INSERT INTO CLIENTE VALUES(1, "JOSÉ DA SILVA", "(14)9985-1341", "AV.SANTO ANTONIO, 312", "VISA", "PAGO" );
INSERT INTO CLIENTE VALUES(2, "MARIANA COSTA", "(14)99625-2443", "AV.SAMPAIO VIDAL, 02", "VISA", "EM PROCESSO" );
INSERT INTO CLIENTE VALUES(3, "FERNANDO BARROS DA SILVA", "(14)99485-4421", "AV.RIO BRANCO, 12", "VISA", "DEVENDO" );

DELETE FROM CLIENTE
WHERE STATUSCLI = "EM PROCESSO";

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CODCLI);

CREATE TABLE PEDIDO(
NUMPED INT NOT NULL,
DTELABPED VARCHAR(35),
CODCLI INT NOT NULL
);

INSERT INTO PEDIDO VALUES(432, "20/12/2023", 1);
INSERT INTO PEDIDO VALUES(453, "12/11/2022", 2);
INSERT INTO PEDIDO VALUES(563, "31/12/2026", 3);

DELETE FROM PEDIDO
WHERE DTELABPED = "12/11/2022";

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMPED);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (CODCLI) REFERENCES CLIENTE(CODCLI);

CREATE TABLE PEDIDOPRODUTO(
NUMPED INT NOT NULL,
CODPROD INT NOT NULL,
QTDEITEMPROD VARCHAR(35)
);

INSERT INTO PEDIDOPRODUTO VALUES(432, 32, 34);
INSERT INTO PEDIDOPRODUTO VALUES(453, 12, 54);
INSERT INTO PEDIDOPRODUTO VALUES(563, 24, 65);

DELETE FROM PEDIDOPRODUTO
WHERE QTDEITEMPROD = "54";

ALTER TABLE PEDIDOPRODUTO ADD CONSTRAINT PK_PEDIDOPRODUTO PRIMARY KEY (NUMPED);
ALTER TABLE PEDIDOPRODUTO ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (CODPROD) REFERENCES PRODUTO (CODPROD);

CREATE TABLE PRODUTO(
CODPROD INT NOT NULL,
NOMEPROD VARCHAR(35),
PRECOPROD VARCHAR(14),
CODCAT INT NOT NULL
);

INSERT INTO PRODUTO VALUES(32, "SABONETE", 35, 01);
INSERT INTO PRODUTO VALUES(12, "CLORO", 23, 02);
INSERT INTO PRODUTO VALUES(24, "AMACIANTE", 27, 03);

DELETE FROM PRODUTO
WHERE NOMEPROD = "CLORO";

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (CODPROD);
ALTER TABLE PRODUTO ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (CODCAT) REFERENCES CATEGORIA (CODCAT);

CREATE TABLE CATEGORIA(
CODCAT INT NOT NULL,
DESCAT VARCHAR(35)
);

INSERT INTO CATEGORIA VALUES(01, "20/12/2025");
INSERT INTO CATEGORIA VALUES(02, "31/12/2025");
INSERT INTO CATEGORIA VALUES(03, "24/12/2025");

DELETE FROM CATEGORIA
WHERE CODCAT = 03;

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CODCAT);