CREATE DATABASE PASSAGENSAEREAS;
USE PASSAGENSAEREAS;

CREATE TABLE VOO(
NUMERO_VOO INT NOT NULL,
PILOTO_VOO CHAR(3),
AEROPORTO_PARTIDA_VOO VARCHAR(25),
AEROPORTO_CHEGADA_VOO VARCHAR(25),
NUMERO_SERIE_AVIAO INT NOT NULL
);

CREATE TABLE AVIAO(
NUMERO_SERIE_AVIAO INT NOT NULL,
MODELO_AVIAO CHAR(5)
);

CREATE TABLE ASSENTO(
COD_ASSENTO INT NOT NULL,
NUMERO_SERIE_AVIAO INT NOT NULL
);

CREATE TABLE ECONOMICO(
COD_ECONOMIO INT NOT NULL,
COD_ASSENTO INT NOT NULL
);

CREATE TABLE EXEUTIVO(
COD_EXEUTIVO INT NOT NULL,
COD_ASSENTO INT NOT NULL
);

CREATE TABLE PASSAGEIRO(
CPF INT NOT NULL,
NOME_PASSAGEIRO VARCHAR(20),
COD_ASSENTO INT NOT NULL
);

ALTER TABLE VOO ADD CONSTRAINT PK_VOO PRIMARY KEY (NUMERO_VOO);
ALTER TABLE AVIAO ADD CONSTRAINT PK_AVIAO PRIMARY KEY (NUMERO_SERIE_AVIAO);
ALTER TABLE ASSENTO ADD CONSTRAINT PK_ASSENTO PRIMARY KEY (COD_ASSENTO);
ALTER TABLE ECONOMICO ADD CONSTRAINT PK_ECONOMICO PRIMARY KEY (COD_ECONOMICO);
ALTER TABLE EXECUTIVO ADD CONSTRAINT PK_EXECUTIVO PRIMARY KEY (COD_EXECUTIVO);
ALTER TABLE PASSAGEIRO ADD CONSTRAINT PK_PASSAGEIRO PRIMARY KEY (CPF);

ALTER TABLE ECONOMICO ADD CONSTRAINT FK_ECONOMICO FOREIGN KEY (COD_ASSENTO) REFERENCES ECONOMICO(COD_ECONOMICO);
ALTER TABLE EXEUTIVO ADD CONSTRAINT FK_EXECUTIVO FOREIGN KEY (COD_ASSENTO) REFERENCES EXECUTIVO(COD_EXECUTIVO);


